<script setup>
import { computed } from "vue";
import {
    House,
    Gauge,
    Wrench,
    ClipboardList,
    LogOut,
    Menu,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    User,
    TriangleAlert,
    ShieldCheck,
    Bell,
    Sun,
    Moon,
    Droplet,
    Droplets,
    Calendar,
    History,
    Megaphone,
    Phone,
    Mail,
    Lock,
    Check,
    X,
    ArrowRight,
    TrendingUp,
    TrendingDown,
    Minus,
    Users,
    MapPin,
    Star,
    FileText,
    CreditCard,
    Zap,
    Sparkles,
    Download,
    ListFilter,
    Search,
    Plus,
    MessageCircle,
} from "@lucide/vue";

const props = defineProps({
    name: {
        type: String,
        required: true,
    },
    size: {
        type: Number,
        default: 20,
    },
});

const icons = {
    home: House,
    gauge: Gauge,
    wrench: Wrench,
    "clipboard-list": ClipboardList,
    "log-out": LogOut,
    menu: Menu,
    "chevron-down": ChevronDown,
    "chevron-left": ChevronLeft,
    "chevron-right": ChevronRight,
    user: User,
    "alert-triangle": TriangleAlert,
    "shield-check": ShieldCheck,
    bell: Bell,
    sun: Sun,
    moon: Moon,
    droplet: Droplet,
    droplets: Droplets,
    calendar: Calendar,
    history: History,
    megaphone: Megaphone,
    phone: Phone,
    mail: Mail,
    lock: Lock,
    check: Check,
    x: X,
    "arrow-right": ArrowRight,
    "trending-up": TrendingUp,
    "trending-down": TrendingDown,
    minus: Minus,
    users: Users,
    "map-pin": MapPin,
    star: Star,
    "file-text": FileText,
    "credit-card": CreditCard,
    zap: Zap,
    sparkles: Sparkles,
    download: Download,
    filter: ListFilter,
    search: Search,
    plus: Plus,
    "message-circle": MessageCircle,
};

const component = computed(() => icons[props.name] ?? null);
</script>

<template>
    <component :is="component" v-if="component" :size="size" :stroke-width="1.8" />
</template>
